import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-tiptap/styles.css';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { ConvexClientProvider } from '@/providers/convex-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NuqsAdapter>
          <ConvexClientProvider>
            {children}
            <Toaster />
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
